encoding: "utf-8"
markdown: kramdown
safe: false
paginate: 12
paginate_path: "/blog/page:num/"
paginate_category_basepath: "/:name/"
paginate_category_layout: "category.html"
sitemap:
  posts_per_page: 500
exclude:
  - .git
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - bower.json
  - Gruntfile.js
  - node_modules
  - bower_components
  - less
  - js
gems:
  - jekyll-paginate
  - jekyll-paginate-categories
